table Analytics

	column Refrigerante
		dataType: string
		summarizeBy: none
		sourceColumn: Refrigerante

	column Compuesto
		dataType: string
		summarizeBy: none
		sourceColumn: Compuesto

	column Seguridad
		dataType: string
		summarizeBy: none
		sourceColumn: Seguridad

	column GWP
		dataType: double
		summarizeBy: none
		sourceColumn: GWP

	column ODP
		dataType: double
		summarizeBy: none
		sourceColumn: ODP

	column Estado
		dataType: string
		summarizeBy: none
		sourceColumn: Estado

	measure KPI_Refrigerantes = COUNTROWS(Analytics)
		formatString: #,0.00
		displayFolder: KPIs

	measure KPI_GWPPromedio = AVERAGE(Analytics[GWP])
		formatString: #,0.00
		displayFolder: KPIs

	measure KPI_ODPPromedio = AVERAGE(Analytics[ODP])
		formatString: #,0.00
		displayFolder: KPIs

	measure KPI_SinODP = CALCULATE(COUNTROWS(Analytics), Analytics[ODP] = 0)
		formatString: #,0
		displayFolder: KPIs

	partition Analytics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "analytics.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"Refrigerante", type text}, {"Compuesto", type text}, {"Seguridad", type text}, {"GWP", type number}, {"ODP", type number}, {"Estado", type text}}, "en-US")
				in
				    Typed
